
sudo: required
dist: trusty

language:
  - cpp

compiler:
  - gcc

before_install:
  - pip install --user cpp-coveralls
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  apt:
    packages:
      - ruby
  coverity_scan:
    project:
      name: "igormironchik/read-excel"
      description: "Build submitted via Travis CI"
    notification_email: igor.mironchik@gmail.com
    build_command: ruby build.rb
    branch_pattern: coverity_scan

before_script:
  - sudo gem install Mxx_ru

script:
- |
  if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then \
    ruby build.rb enable_coverage || { exit 1; }; \
    coveralls --build-root . --gcov-options '\-lp' -e sample -e test -e lib || { exit 1; }; \
    fi
