
sudo: required
dist: trusty

language:
  - cpp

compiler:
  - gcc

before_install:
  - pip install --user cpp-coveralls
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  apt:
    packages:
      - ruby
  coverity_scan:
    project:
      name: "igormironchik/read-excel"
      description: "Build submitted via Travis CI"
    notification_email: igor.mironchik@gmail.com
    build_command_prepend: echo 'Starting prebuild step...'; mkdir build; cd build; cmake ..; echo 'Prebuild step finished...';
    build_command: make
    branch_pattern: coverity_scan

before_script:
  - sudo gem install Mxx_ru

script:
- |
  if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then \
    mkdir build || { exit 1; }; \
    cd build || { exit 1; }; \
    cmake -DENABLE_COVERAGE=ON .. || { exit 1; }; \
    make || { exit 1; }; \
    ctest --output-on-failure || { exit 1; }; \
    cd .. || { exit 1; }; \
    coveralls --build-root build --gcov-options '\-lp' \
    -e sample -e test -e lib -e build/CMakeFiles || { exit 1; }; \
    fi
