
sudo: required
dist: trusty

language:
  - cpp

compiler:
  - gcc

before_install:
  - pip install --user cpp-coveralls
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  apt:
    packages:
      - ruby
  coverity_scan:
    project:
      name: "igormironchik/read-excel"
      description: "Build submitted via Travis CI"
	notification_email: igor.mironchik@gmail.com
    build_command_prepend: echo 'Starting prebuild step...'; gem install Mxx_ru; echo 'Prebuild step finished...';
    build_command: ruby build.rb
    branch_pattern: coverity_scan

before_script:
  - sudo gem install Mxx_ru

script:
  - ruby build.rb enable_coverage
  - coveralls --build-root . --gcov-options '\-lp' -e sample -e test -e lib
